# Generated by Django 4.2 on 2023-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menuitem_named_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
