# Generated by Django 4.2 on 2023-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menuitem_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
